### ISSUE TITLE
Create Login Page to Look Like Marist

### ISSUE THREAD

**Issue by emilydoran1** [cc12698/Marist-Syllabus-Evaluator-Cap2020#16]

**Comment by T0mmyBurda** [comment]
If we use the Marist log-in, we will probably be re-directing to the Marist log-in page like outlook does. May want to wait to start this until we know its needed

**Comment by cc12698** [comment]
@T0mmyBurda that will be the login page, we will use cas to authenticate the login when the time comes. won't be redirecting anywhere else
